title: Meline's Portfolio
description: Finance graduate exploring tech | Cloud Computing | Digital Transformation
url: "https://meline-bit.github.io/Meline-lbt.github.io"
baseurl: "" # Leave this blank if it's a user/org site

author: Meline
email: nasambucamelinen@gmail.com

theme: minima

github_username: meline-bit
linkedin_username:www.linkedin.com/in/camelinenyongesa

markdown: kramdown
plugins:
  - jekyll-feed
